## Choice of a embeddings model

In [1]:
from sentence_transformers import SentenceTransformer

model = SentenceTransformer("all-MiniLM-L6-v2")

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

In [2]:
model

SentenceTransformer(
  (0): Transformer({'transformer_task': 'feature-extraction', 'modality_config': {'text': {'method': 'forward', 'method_output_name': 'last_hidden_state'}}, 'module_output_name': 'token_embeddings', 'architecture': 'BertModel'})
  (1): Pooling({'embedding_dimension': 384, 'pooling_mode': 'mean', 'include_prompt': True})
  (2): Normalize({})
)

In [3]:
q1 = "Can I still join the course after the start date?"
v1 = model.encode(q1)
v1

array([ 2.13903990e-02, -7.39799812e-02,  1.42065180e-03,  2.13816483e-02,
        2.45113000e-02,  3.15582491e-02, -1.10839739e-01, -1.05017483e-01,
       -6.18259013e-02, -6.42313017e-03,  3.72400577e-03,  9.06393602e-02,
       -9.49939992e-03,  6.53977171e-02,  1.10946624e-02, -2.10097507e-02,
       -3.35125588e-02, -4.31677438e-02,  9.96346120e-03,  1.41969975e-02,
       -6.40414879e-02, -7.04178866e-03, -7.91187808e-02,  5.80030791e-02,
        1.30210677e-03,  4.19733441e-03,  5.70979267e-02,  6.39447644e-02,
        2.49902867e-02, -3.95876840e-02, -3.79506722e-02,  2.70394180e-02,
        1.79423410e-02,  1.72272567e-02,  3.43311243e-02,  9.29055829e-03,
        5.86054809e-02, -4.97789569e-02, -5.05372230e-03,  4.34328504e-02,
       -1.56622995e-02, -2.97534354e-02, -5.13324002e-03,  5.13414927e-02,
        6.16058800e-03,  6.86980933e-02, -1.29505759e-02, -5.61938770e-02,
       -1.08264890e-02,  5.96684068e-02,  5.29939719e-02, -3.42755169e-02,
       -4.15274091e-02, -

In [4]:
d  = "You don't need to register. You're accepted. You can also just start learning and submitting homework without registering."
dv = model.encode(d)
dv

array([-4.81206775e-02, -1.29942074e-01, -4.86808317e-03,  1.37495529e-02,
       -8.51100869e-03,  6.97841570e-02, -7.55665125e-03,  4.09571566e-02,
       -1.02165632e-01, -3.45050246e-02,  2.85521764e-02, -5.81430420e-02,
       -1.85113382e-02, -3.17838937e-02,  5.29631339e-02,  3.96292657e-02,
       -9.84595902e-03, -6.45324662e-02,  7.05097467e-02, -6.39588907e-02,
       -3.55156958e-02, -1.75490174e-02, -3.58401388e-02,  5.50847617e-04,
        3.38445231e-02,  2.91763078e-02,  3.24278362e-02, -5.64807141e-03,
        8.42593312e-02,  5.90306185e-02,  2.08773017e-02, -5.44831250e-03,
        2.98403483e-02,  1.30820479e-02,  6.36077598e-02, -3.06394100e-02,
        6.28460050e-02, -1.69217885e-02, -4.65758219e-02, -5.13762161e-02,
       -3.81560959e-02, -7.01197386e-02, -9.55517590e-02,  5.01640476e-02,
        8.57913122e-03,  1.19207427e-02, -1.40597690e-02, -7.98978005e-03,
       -3.44238505e-02, -2.34269928e-02,  2.89465990e-02,  2.68904790e-02,
       -4.87408936e-02, -

In [5]:
q2 = "How to install Docker on Windows?"
v2 = model.encode(q2)
v2

array([-2.35678628e-02,  7.85556287e-02,  2.33792439e-02, -6.72474504e-03,
       -2.58874744e-02,  1.18257208e-02,  5.29584475e-04,  9.57363565e-03,
        6.23929426e-02,  2.91427169e-02, -4.18229997e-02, -6.62150010e-02,
       -2.76613496e-02,  5.41519076e-02, -1.92781780e-02, -2.46782042e-02,
       -2.89791403e-03,  8.40462148e-02,  1.03637371e-02, -6.35399623e-03,
       -1.20814152e-01,  1.80162974e-02, -5.70900999e-02, -7.92970508e-02,
       -9.25545953e-03, -3.24046537e-02, -1.95662826e-02, -2.65410841e-02,
       -9.41328611e-03,  4.31234576e-02, -2.08749883e-02, -7.86434188e-02,
        9.19373930e-02, -3.75260715e-03,  5.13070934e-02, -5.73644228e-03,
        5.61954416e-02,  3.73761728e-03, -6.88236728e-02, -4.57000174e-02,
        2.83075776e-02, -3.49764749e-02, -5.55282750e-04, -3.09769846e-02,
        4.34275344e-02, -4.48056534e-02,  6.84109330e-02,  4.14185692e-04,
        5.82685769e-02,  6.66982532e-02, -8.95875618e-02, -2.69941632e-02,
        1.06746666e-02, -

In [6]:
v1.dot(dv)

np.float32(0.323324)

In [7]:
v2.dot(dv)

np.float32(0.019730432)

## Embeddings on Dataset

In [8]:
import os, sys

module_dir = '../../01-agentic-rag/code'
sys.path.insert(0, module_dir)


In [9]:
from ingest import load_faq_data

documents = load_faq_data()

In [10]:
texts = []

for doc in documents:
    text = doc["question"] + " " + doc["answer"]
    texts.append(text)

In [11]:
from tqdm.auto import tqdm

In [12]:
batch_size = 50
vectors = []

for i in tqdm(range(0, len(texts), batch_size)):
    batch = texts[i:i + batch_size]
    batch_vectors = model.encode(batch)
    vectors.extend(batch_vectors)

len(vectors)

  0%|          | 0/27 [00:00<?, ?it/s]

1350

In [13]:
import numpy as np
X = np.array(vectors)

In [14]:
X.shape

(1350, 384)

## Vector Search 

In [15]:
query = "Can I still join the course after the start date?"
v_query = model.encode(query)

In [16]:
scores = X.dot(v_query)
scores

array([ 0.48740578,  0.20991933,  0.7629412 , ..., -0.08637966,
        0.03759791, -0.03037041], shape=(1350,), dtype=float32)

In [17]:
# # looping over docs for scores
scores = [v_query.dot(X[i]) for i in range(len(X))]

In [18]:
## Best match 
idx = np.argmax(scores)
idx, scores[idx]

(np.int64(2), np.float32(0.7629412))

In [19]:
documents[idx]

{'course': 'data-engineering-zoomcamp',
 'section': 'General Course-Related Questions',
 'question': 'Course: Can I still join the course after the start date?',
 'answer': "Yes, even if you don't register, you're still eligible to submit the homework.\n\nBe aware, however, that there will be deadlines for turning in homeworks and the final projects. So don't leave everything for the last minute.",
 'doc_id': '3f1424af17'}

## Top 5 eresults

In [20]:
top5 = np.argsort(scores)[-5:]

In [21]:
top5 = top5[::-1]
top5

array([  2, 625, 907, 538,   7])

In [22]:
for idx in top5:
    print(idx)
    print(scores[idx])
    print(documents[idx])
    print()

2
0.7629412
{'course': 'data-engineering-zoomcamp', 'section': 'General Course-Related Questions', 'question': 'Course: Can I still join the course after the start date?', 'answer': "Yes, even if you don't register, you're still eligible to submit the homework.\n\nBe aware, however, that there will be deadlines for turning in homeworks and the final projects. So don't leave everything for the last minute.", 'doc_id': '3f1424af17'}

625
0.7579371
{'course': 'mlops-zoomcamp', 'section': 'General Course-Related Questions', 'question': 'Course - Can I still join the course after the start date?', 'answer': "Yes, even if you don't register, you're still eligible to submit the homeworks as long as the form is still open and accepting submissions.\n\nBe aware, however, that there will be deadlines for turning in the final projects. So don't leave everything to the last minute.", 'doc_id': '2d8b16c2a0'}

907
0.7192132
{'course': 'machine-learning-zoomcamp', 'section': 'General Course-Related Q

## Vector Search with minsearch

In [23]:
from minsearch import VectorSearch

vindex = VectorSearch(keyword_fields=["course"])
vindex.fit(X, documents)

In [24]:
query = "I just discovered the course. Can I still join it?"
query_vector = model.encode(query)

results = vindex.search(query_vector, num_results=5)

In [25]:
results[0]

{'course': 'llm-zoomcamp',
 'section': 'General Course-Related Questions',
 'question': 'I just discovered the course. Can I still join?',
 'answer': 'Yes, but if you want to receive a certificate, you need to submit your project while we’re still accepting submissions.',
 'doc_id': '74eb249bbf'}

### Filtering by course 

In [26]:
results = vindex.search(
    query_vector,
    filter_dict={"course": "llm-zoomcamp"},
    num_results=5
)

In [27]:
results[0]

{'course': 'llm-zoomcamp',
 'section': 'General Course-Related Questions',
 'question': 'I just discovered the course. Can I still join?',
 'answer': 'Yes, but if you want to receive a certificate, you need to submit your project while we’re still accepting submissions.',
 'doc_id': '74eb249bbf'}

## RAG With Vector Search

In [28]:
from dotenv import load_dotenv
from openai import OpenAI

load_dotenv()
openai_client = OpenAI()

In [29]:
from ingest import load_faq_data, build_index

documents = load_faq_data()
index = build_index(documents)

In [30]:
from rag_helper import RAGBase

assistant = RAGBase(
    index=index,
    llm_client=openai_client,
)

In [31]:
query = "I just found out about the program, can I still sign up?"
assistant.rag(query)

'Yes, but if you want to receive a certificate, you need to submit your project while submissions are still being accepted.'

In [32]:
import os, sys

module_dir = '../code/'
sys.path.insert(0, module_dir)

In [33]:
class RAGVector(RAGBase):

    def __init__(self, embedder, **kwargs):
        super().__init__(**kwargs)
        self.embedder = embedder

    def search(self, query, num_results=5):
        query_vector = self.embedder.encode(query)
        filter_dict = {'course': self.course}

        return self.index.search(
            query_vector,
            num_results=num_results,
            filter_dict=filter_dict
        )

In [34]:
vector_assistant = RAGVector(
    embedder=model,
    index=vindex,
    llm_client=openai_client,
)

In [35]:
query = 'I just found out about the program, can I still sign up?'
vector_assistant.rag(query)

'Yes, you can still join. If you want to receive a certificate, make sure to submit your project while submissions are still open.'

## Vector Search with sqlitesearch

In [36]:
from sqlitesearch import VectorSearchIndex

vs_index = VectorSearchIndex(
    keyword_fields=["course"],
    mode="ivf",
    db_path="faq_vectors2.db"
)

In [37]:
vs_index.fit(vectors, documents)

In [39]:
query = "I just discovered the course. Can I still join it?"
query_vector = model.encode(query)

results = vs_index.search(query_vector, num_results=5)

In [41]:
results[0]

{'course': 'llm-zoomcamp',
 'section': 'General Course-Related Questions',
 'question': 'I just discovered the course. Can I still join?',
 'answer': 'Yes, but if you want to receive a certificate, you need to submit your project while we’re still accepting submissions.',
 'doc_id': '74eb249bbf'}

In [42]:
results = vs_index.search(
    query_vector,
    filter_dict={"course": "llm-zoomcamp"},
    num_results=5
)

In [44]:
results[0]

{'course': 'llm-zoomcamp',
 'section': 'General Course-Related Questions',
 'question': 'I just discovered the course. Can I still join?',
 'answer': 'Yes, but if you want to receive a certificate, you need to submit your project while we’re still accepting submissions.',
 'doc_id': '74eb249bbf'}

In [45]:
vs_index.close()

### Reopening the index

In [46]:
from sentence_transformers import SentenceTransformer
from sqlitesearch import VectorSearchIndex

model = SentenceTransformer("all-MiniLM-L6-v2")

vs_index = VectorSearchIndex(
    keyword_fields=["course"],
    mode="ivf",
    db_path="faq_vectors2.db"
)

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

In [47]:
query_vector = model.encode("How do I run Kafka?")
results = vs_index.search(query_vector, num_results=5)

In [48]:
from sentence_transformers import SentenceTransformer
from sqlitesearch import VectorSearchIndex

model = SentenceTransformer("all-MiniLM-L6-v2")

vs_index = VectorSearchIndex(
    keyword_fields=["course"],
    mode="ivf",
    db_path="faq_vectors2.db"
)

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

In [49]:
from rag_helper import RAGBase
from dotenv import load_dotenv
from openai import OpenAI

load_dotenv()
openai_client = OpenAI()

class RAGVector(RAGBase):

    def __init__(self, embedder, **kwargs):
        super().__init__(**kwargs)
        self.embedder = embedder

    def search(self, query, num_results=5):
        query_vector = self.embedder.encode(query)
        filter_dict = {"course": self.course}

        return self.index.search(
            query_vector,
            num_results=num_results,
            filter_dict=filter_dict
        )

vector_assistant = RAGVector(
    embedder=model,
    index=vs_index,
    llm_client=openai_client,
)

In [50]:
vector_assistant.rag("the program has already begun, can I still sign up?")

'Yes — you can still join. You don’t need to wait for a confirmation email; you’re accepted and can start learning right away, as long as the submission form is still open if you want to submit homework or a project.'

In [51]:
vs_index.close()